# inference differs:
#   requires.system_deps: added libstdc++; removed npm (vs inferred)
#  deps diff:
#   +wget -O - https://unofficial-builds.nodejs.org/download/release/v16.12.0/node-v16.12.0-linux-x64-musl.tar.gz | tar xzf - --strip-components=1 -C /usr/local/
#  build diff:
#   -/usr/bin/npx --package=npm@8.5.2 -c 'npm pack'
#   +cd /src && /usr/local/bin/npm pack
flow:
  location:
    repo: https://github.com/winstonjs/winston-daily-rotate-file
    ref: d2182f14ef45e2131f226a4d448e57934c547abc
    dir: ""
  src:
    - uses: git-checkout
  deps:
    - uses: npm/install-node
      with:
        nodeVersion: "16.12.0"
  build:
    - runs: cd /src && /usr/local/bin/npm pack
  output_dir: ""
  requires:
    system_deps:
      - libstdc++
