// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: events.proto

package sysgraph

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceEvent_EventType int32

const (
	ResourceEvent_EVENT_TYPE_UNSPECIFIED ResourceEvent_EventType = 0
	// An input event.
	ResourceEvent_EVENT_TYPE_INPUT ResourceEvent_EventType = 1
	// An output event.
	ResourceEvent_EVENT_TYPE_OUTPUT ResourceEvent_EventType = 2
)

// Enum value maps for ResourceEvent_EventType.
var (
	ResourceEvent_EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_INPUT",
		2: "EVENT_TYPE_OUTPUT",
	}
	ResourceEvent_EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_INPUT":       1,
		"EVENT_TYPE_OUTPUT":      2,
	}
)

func (x ResourceEvent_EventType) Enum() *ResourceEvent_EventType {
	p := new(ResourceEvent_EventType)
	*p = x
	return p
}

func (x ResourceEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[0].Descriptor()
}

func (ResourceEvent_EventType) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[0]
}

func (x ResourceEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SysGraphEvent struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ActionId    *string                `protobuf:"bytes,1,opt,name=action_id,json=actionId"`
	xxx_hidden_Timestamp   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp"`
	xxx_hidden_Event       isSysGraphEvent_Event  `protobuf_oneof:"event"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SysGraphEvent) Reset() {
	*x = SysGraphEvent{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysGraphEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysGraphEvent) ProtoMessage() {}

func (x *SysGraphEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SysGraphEvent) GetActionId() string {
	if x != nil {
		if x.xxx_hidden_ActionId != nil {
			return *x.xxx_hidden_ActionId
		}
		return ""
	}
	return ""
}

func (x *SysGraphEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *SysGraphEvent) GetResourceEvent() *ResourceEvent {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*sysGraphEvent_ResourceEvent); ok {
			return x.ResourceEvent
		}
	}
	return nil
}

func (x *SysGraphEvent) GetChildEvent() *ChildEvent {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*sysGraphEvent_ChildEvent); ok {
			return x.ChildEvent
		}
	}
	return nil
}

func (x *SysGraphEvent) GetExecEvent() *ExecEvent {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*sysGraphEvent_ExecEvent); ok {
			return x.ExecEvent
		}
	}
	return nil
}

func (x *SysGraphEvent) GetMetadataEvent() *MetadataEvent {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*sysGraphEvent_MetadataEvent); ok {
			return x.MetadataEvent
		}
	}
	return nil
}

func (x *SysGraphEvent) GetEndEvent() *EndEvent {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*sysGraphEvent_EndEvent); ok {
			return x.EndEvent
		}
	}
	return nil
}

func (x *SysGraphEvent) GetStartEvent() *StartEvent {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*sysGraphEvent_StartEvent); ok {
			return x.StartEvent
		}
	}
	return nil
}

func (x *SysGraphEvent) GetPipeEvent() *PipeEvent {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*sysGraphEvent_PipeEvent); ok {
			return x.PipeEvent
		}
	}
	return nil
}

func (x *SysGraphEvent) GetDupEvent() *DupEvent {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*sysGraphEvent_DupEvent); ok {
			return x.DupEvent
		}
	}
	return nil
}

func (x *SysGraphEvent) SetActionId(v string) {
	x.xxx_hidden_ActionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *SysGraphEvent) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *SysGraphEvent) SetResourceEvent(v *ResourceEvent) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &sysGraphEvent_ResourceEvent{v}
}

func (x *SysGraphEvent) SetChildEvent(v *ChildEvent) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &sysGraphEvent_ChildEvent{v}
}

func (x *SysGraphEvent) SetExecEvent(v *ExecEvent) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &sysGraphEvent_ExecEvent{v}
}

func (x *SysGraphEvent) SetMetadataEvent(v *MetadataEvent) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &sysGraphEvent_MetadataEvent{v}
}

func (x *SysGraphEvent) SetEndEvent(v *EndEvent) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &sysGraphEvent_EndEvent{v}
}

func (x *SysGraphEvent) SetStartEvent(v *StartEvent) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &sysGraphEvent_StartEvent{v}
}

func (x *SysGraphEvent) SetPipeEvent(v *PipeEvent) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &sysGraphEvent_PipeEvent{v}
}

func (x *SysGraphEvent) SetDupEvent(v *DupEvent) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &sysGraphEvent_DupEvent{v}
}

func (x *SysGraphEvent) HasActionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SysGraphEvent) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *SysGraphEvent) HasEvent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Event != nil
}

func (x *SysGraphEvent) HasResourceEvent() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*sysGraphEvent_ResourceEvent)
	return ok
}

func (x *SysGraphEvent) HasChildEvent() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*sysGraphEvent_ChildEvent)
	return ok
}

func (x *SysGraphEvent) HasExecEvent() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*sysGraphEvent_ExecEvent)
	return ok
}

func (x *SysGraphEvent) HasMetadataEvent() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*sysGraphEvent_MetadataEvent)
	return ok
}

func (x *SysGraphEvent) HasEndEvent() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*sysGraphEvent_EndEvent)
	return ok
}

func (x *SysGraphEvent) HasStartEvent() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*sysGraphEvent_StartEvent)
	return ok
}

func (x *SysGraphEvent) HasPipeEvent() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*sysGraphEvent_PipeEvent)
	return ok
}

func (x *SysGraphEvent) HasDupEvent() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*sysGraphEvent_DupEvent)
	return ok
}

func (x *SysGraphEvent) ClearActionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ActionId = nil
}

func (x *SysGraphEvent) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

func (x *SysGraphEvent) ClearEvent() {
	x.xxx_hidden_Event = nil
}

func (x *SysGraphEvent) ClearResourceEvent() {
	if _, ok := x.xxx_hidden_Event.(*sysGraphEvent_ResourceEvent); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *SysGraphEvent) ClearChildEvent() {
	if _, ok := x.xxx_hidden_Event.(*sysGraphEvent_ChildEvent); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *SysGraphEvent) ClearExecEvent() {
	if _, ok := x.xxx_hidden_Event.(*sysGraphEvent_ExecEvent); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *SysGraphEvent) ClearMetadataEvent() {
	if _, ok := x.xxx_hidden_Event.(*sysGraphEvent_MetadataEvent); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *SysGraphEvent) ClearEndEvent() {
	if _, ok := x.xxx_hidden_Event.(*sysGraphEvent_EndEvent); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *SysGraphEvent) ClearStartEvent() {
	if _, ok := x.xxx_hidden_Event.(*sysGraphEvent_StartEvent); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *SysGraphEvent) ClearPipeEvent() {
	if _, ok := x.xxx_hidden_Event.(*sysGraphEvent_PipeEvent); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *SysGraphEvent) ClearDupEvent() {
	if _, ok := x.xxx_hidden_Event.(*sysGraphEvent_DupEvent); ok {
		x.xxx_hidden_Event = nil
	}
}

const SysGraphEvent_Event_not_set_case case_SysGraphEvent_Event = 0
const SysGraphEvent_ResourceEvent_case case_SysGraphEvent_Event = 3
const SysGraphEvent_ChildEvent_case case_SysGraphEvent_Event = 4
const SysGraphEvent_ExecEvent_case case_SysGraphEvent_Event = 5
const SysGraphEvent_MetadataEvent_case case_SysGraphEvent_Event = 6
const SysGraphEvent_EndEvent_case case_SysGraphEvent_Event = 7
const SysGraphEvent_StartEvent_case case_SysGraphEvent_Event = 8
const SysGraphEvent_PipeEvent_case case_SysGraphEvent_Event = 9
const SysGraphEvent_DupEvent_case case_SysGraphEvent_Event = 10

func (x *SysGraphEvent) WhichEvent() case_SysGraphEvent_Event {
	if x == nil {
		return SysGraphEvent_Event_not_set_case
	}
	switch x.xxx_hidden_Event.(type) {
	case *sysGraphEvent_ResourceEvent:
		return SysGraphEvent_ResourceEvent_case
	case *sysGraphEvent_ChildEvent:
		return SysGraphEvent_ChildEvent_case
	case *sysGraphEvent_ExecEvent:
		return SysGraphEvent_ExecEvent_case
	case *sysGraphEvent_MetadataEvent:
		return SysGraphEvent_MetadataEvent_case
	case *sysGraphEvent_EndEvent:
		return SysGraphEvent_EndEvent_case
	case *sysGraphEvent_StartEvent:
		return SysGraphEvent_StartEvent_case
	case *sysGraphEvent_PipeEvent:
		return SysGraphEvent_PipeEvent_case
	case *sysGraphEvent_DupEvent:
		return SysGraphEvent_DupEvent_case
	default:
		return SysGraphEvent_Event_not_set_case
	}
}

type SysGraphEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The action id of the action that this event is associated with.
	// This action id should be unique within a set of events.
	ActionId *string
	// The time that this event occurred.
	Timestamp *timestamppb.Timestamp
	// The event that occurred.

	// Fields of oneof xxx_hidden_Event:
	// An resource event.
	ResourceEvent *ResourceEvent
	// A child event.
	ChildEvent *ChildEvent
	// An exec event.
	ExecEvent *ExecEvent
	// A metadata event.
	MetadataEvent *MetadataEvent
	// An action end event.
	EndEvent *EndEvent
	// An action end event.
	StartEvent *StartEvent
	PipeEvent  *PipeEvent
	DupEvent   *DupEvent
	// -- end of xxx_hidden_Event
}

func (b0 SysGraphEvent_builder) Build() *SysGraphEvent {
	m0 := &SysGraphEvent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ActionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_ActionId = b.ActionId
	}
	x.xxx_hidden_Timestamp = b.Timestamp
	if b.ResourceEvent != nil {
		x.xxx_hidden_Event = &sysGraphEvent_ResourceEvent{b.ResourceEvent}
	}
	if b.ChildEvent != nil {
		x.xxx_hidden_Event = &sysGraphEvent_ChildEvent{b.ChildEvent}
	}
	if b.ExecEvent != nil {
		x.xxx_hidden_Event = &sysGraphEvent_ExecEvent{b.ExecEvent}
	}
	if b.MetadataEvent != nil {
		x.xxx_hidden_Event = &sysGraphEvent_MetadataEvent{b.MetadataEvent}
	}
	if b.EndEvent != nil {
		x.xxx_hidden_Event = &sysGraphEvent_EndEvent{b.EndEvent}
	}
	if b.StartEvent != nil {
		x.xxx_hidden_Event = &sysGraphEvent_StartEvent{b.StartEvent}
	}
	if b.PipeEvent != nil {
		x.xxx_hidden_Event = &sysGraphEvent_PipeEvent{b.PipeEvent}
	}
	if b.DupEvent != nil {
		x.xxx_hidden_Event = &sysGraphEvent_DupEvent{b.DupEvent}
	}
	return m0
}

type case_SysGraphEvent_Event protoreflect.FieldNumber

func (x case_SysGraphEvent_Event) String() string {
	md := file_events_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isSysGraphEvent_Event interface {
	isSysGraphEvent_Event()
}

type sysGraphEvent_ResourceEvent struct {
	// An resource event.
	ResourceEvent *ResourceEvent `protobuf:"bytes,3,opt,name=resource_event,json=resourceEvent,oneof"`
}

type sysGraphEvent_ChildEvent struct {
	// A child event.
	ChildEvent *ChildEvent `protobuf:"bytes,4,opt,name=child_event,json=childEvent,oneof"`
}

type sysGraphEvent_ExecEvent struct {
	// An exec event.
	ExecEvent *ExecEvent `protobuf:"bytes,5,opt,name=exec_event,json=execEvent,oneof"`
}

type sysGraphEvent_MetadataEvent struct {
	// A metadata event.
	MetadataEvent *MetadataEvent `protobuf:"bytes,6,opt,name=metadata_event,json=metadataEvent,oneof"`
}

type sysGraphEvent_EndEvent struct {
	// An action end event.
	EndEvent *EndEvent `protobuf:"bytes,7,opt,name=end_event,json=endEvent,oneof"`
}

type sysGraphEvent_StartEvent struct {
	// An action end event.
	StartEvent *StartEvent `protobuf:"bytes,8,opt,name=start_event,json=startEvent,oneof"`
}

type sysGraphEvent_PipeEvent struct {
	PipeEvent *PipeEvent `protobuf:"bytes,9,opt,name=pipe_event,json=pipeEvent,oneof"`
}

type sysGraphEvent_DupEvent struct {
	DupEvent *DupEvent `protobuf:"bytes,10,opt,name=dup_event,json=dupEvent,oneof"`
}

func (*sysGraphEvent_ResourceEvent) isSysGraphEvent_Event() {}

func (*sysGraphEvent_ChildEvent) isSysGraphEvent_Event() {}

func (*sysGraphEvent_ExecEvent) isSysGraphEvent_Event() {}

func (*sysGraphEvent_MetadataEvent) isSysGraphEvent_Event() {}

func (*sysGraphEvent_EndEvent) isSysGraphEvent_Event() {}

func (*sysGraphEvent_StartEvent) isSysGraphEvent_Event() {}

func (*sysGraphEvent_PipeEvent) isSysGraphEvent_Event() {}

func (*sysGraphEvent_DupEvent) isSysGraphEvent_Event() {}

type PipeEvent struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeEvent) Reset() {
	*x = PipeEvent{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeEvent) ProtoMessage() {}

func (x *PipeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PipeEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PipeEvent_builder) Build() *PipeEvent {
	m0 := &PipeEvent{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DupEvent struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OldFd        int32                  `protobuf:"varint,1,opt,name=old_fd,json=oldFd"`
	xxx_hidden_NewFd        int32                  `protobuf:"varint,2,opt,name=new_fd,json=newFd"`
	xxx_hidden_ParentExecId *string                `protobuf:"bytes,3,opt,name=parent_exec_id,json=parentExecId"`
	xxx_hidden_Timestamp    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DupEvent) Reset() {
	*x = DupEvent{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DupEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DupEvent) ProtoMessage() {}

func (x *DupEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DupEvent) GetOldFd() int32 {
	if x != nil {
		return x.xxx_hidden_OldFd
	}
	return 0
}

func (x *DupEvent) GetNewFd() int32 {
	if x != nil {
		return x.xxx_hidden_NewFd
	}
	return 0
}

func (x *DupEvent) GetParentExecId() string {
	if x != nil {
		if x.xxx_hidden_ParentExecId != nil {
			return *x.xxx_hidden_ParentExecId
		}
		return ""
	}
	return ""
}

func (x *DupEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *DupEvent) SetOldFd(v int32) {
	x.xxx_hidden_OldFd = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *DupEvent) SetNewFd(v int32) {
	x.xxx_hidden_NewFd = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *DupEvent) SetParentExecId(v string) {
	x.xxx_hidden_ParentExecId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *DupEvent) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *DupEvent) HasOldFd() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DupEvent) HasNewFd() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DupEvent) HasParentExecId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DupEvent) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *DupEvent) ClearOldFd() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_OldFd = 0
}

func (x *DupEvent) ClearNewFd() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NewFd = 0
}

func (x *DupEvent) ClearParentExecId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ParentExecId = nil
}

func (x *DupEvent) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

type DupEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OldFd *int32
	NewFd *int32
	// We need this field so that we can check if this dup's parent is a pipe or
	// not. The map we can refer to is a map of
	// parent_exec_id (IR action id) -> parent_aid;
	ParentExecId *string
	// The time that the dup action started.
	Timestamp *timestamppb.Timestamp
}

func (b0 DupEvent_builder) Build() *DupEvent {
	m0 := &DupEvent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.OldFd != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_OldFd = *b.OldFd
	}
	if b.NewFd != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_NewFd = *b.NewFd
	}
	if b.ParentExecId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_ParentExecId = b.ParentExecId
	}
	x.xxx_hidden_Timestamp = b.Timestamp
	return m0
}

type ResourceEvent struct {
	state                  protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Resource    *Resource               `protobuf:"bytes,1,opt,name=resource"`
	xxx_hidden_EventType   ResourceEvent_EventType `protobuf:"varint,2,opt,name=event_type,json=eventType,enum=sysgraph.ResourceEvent_EventType"`
	xxx_hidden_IoInfo      *IOInfo                 `protobuf:"bytes,3,opt,name=io_info,json=ioInfo"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResourceEvent) Reset() {
	*x = ResourceEvent{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceEvent) ProtoMessage() {}

func (x *ResourceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResourceEvent) GetResource() *Resource {
	if x != nil {
		return x.xxx_hidden_Resource
	}
	return nil
}

func (x *ResourceEvent) GetEventType() ResourceEvent_EventType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_EventType
		}
	}
	return ResourceEvent_EVENT_TYPE_UNSPECIFIED
}

func (x *ResourceEvent) GetIoInfo() *IOInfo {
	if x != nil {
		return x.xxx_hidden_IoInfo
	}
	return nil
}

func (x *ResourceEvent) SetResource(v *Resource) {
	x.xxx_hidden_Resource = v
}

func (x *ResourceEvent) SetEventType(v ResourceEvent_EventType) {
	x.xxx_hidden_EventType = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ResourceEvent) SetIoInfo(v *IOInfo) {
	x.xxx_hidden_IoInfo = v
}

func (x *ResourceEvent) HasResource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Resource != nil
}

func (x *ResourceEvent) HasEventType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ResourceEvent) HasIoInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_IoInfo != nil
}

func (x *ResourceEvent) ClearResource() {
	x.xxx_hidden_Resource = nil
}

func (x *ResourceEvent) ClearEventType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EventType = ResourceEvent_EVENT_TYPE_UNSPECIFIED
}

func (x *ResourceEvent) ClearIoInfo() {
	x.xxx_hidden_IoInfo = nil
}

type ResourceEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The digest of the resource in canonical format <hash>/<size>.
	Resource *Resource
	// The type of the event.
	EventType *ResourceEvent_EventType
	IoInfo    *IOInfo
}

func (b0 ResourceEvent_builder) Build() *ResourceEvent {
	m0 := &ResourceEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Resource = b.Resource
	if b.EventType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_EventType = *b.EventType
	}
	x.xxx_hidden_IoInfo = b.IoInfo
	return m0
}

type ChildEvent struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ChildActionId *string                `protobuf:"bytes,1,opt,name=child_action_id,json=childActionId"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ChildEvent) Reset() {
	*x = ChildEvent{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildEvent) ProtoMessage() {}

func (x *ChildEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChildEvent) GetChildActionId() string {
	if x != nil {
		if x.xxx_hidden_ChildActionId != nil {
			return *x.xxx_hidden_ChildActionId
		}
		return ""
	}
	return ""
}

func (x *ChildEvent) SetChildActionId(v string) {
	x.xxx_hidden_ChildActionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ChildEvent) HasChildActionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ChildEvent) ClearChildActionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ChildActionId = nil
}

type ChildEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The action id of the child action.
	ChildActionId *string
}

func (b0 ChildEvent_builder) Build() *ChildEvent {
	m0 := &ChildEvent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ChildActionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ChildActionId = b.ChildActionId
	}
	return m0
}

type ExecEvent struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Executable *Resource              `protobuf:"bytes,1,opt,name=executable"`
	xxx_hidden_ExecInfo   *ExecInfo              `protobuf:"bytes,2,opt,name=exec_info,json=execInfo"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ExecEvent) Reset() {
	*x = ExecEvent{}
	mi := &file_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecEvent) ProtoMessage() {}

func (x *ExecEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExecEvent) GetExecutable() *Resource {
	if x != nil {
		return x.xxx_hidden_Executable
	}
	return nil
}

func (x *ExecEvent) GetExecInfo() *ExecInfo {
	if x != nil {
		return x.xxx_hidden_ExecInfo
	}
	return nil
}

func (x *ExecEvent) SetExecutable(v *Resource) {
	x.xxx_hidden_Executable = v
}

func (x *ExecEvent) SetExecInfo(v *ExecInfo) {
	x.xxx_hidden_ExecInfo = v
}

func (x *ExecEvent) HasExecutable() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Executable != nil
}

func (x *ExecEvent) HasExecInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExecInfo != nil
}

func (x *ExecEvent) ClearExecutable() {
	x.xxx_hidden_Executable = nil
}

func (x *ExecEvent) ClearExecInfo() {
	x.xxx_hidden_ExecInfo = nil
}

type ExecEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Executable *Resource
	ExecInfo   *ExecInfo
}

func (b0 ExecEvent_builder) Build() *ExecEvent {
	m0 := &ExecEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Executable = b.Executable
	x.xxx_hidden_ExecInfo = b.ExecInfo
	return m0
}

type MetadataEvent struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key         *string                `protobuf:"bytes,1,opt,name=key"`
	xxx_hidden_Value       *string                `protobuf:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MetadataEvent) Reset() {
	*x = MetadataEvent{}
	mi := &file_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataEvent) ProtoMessage() {}

func (x *MetadataEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MetadataEvent) GetKey() string {
	if x != nil {
		if x.xxx_hidden_Key != nil {
			return *x.xxx_hidden_Key
		}
		return ""
	}
	return ""
}

func (x *MetadataEvent) GetValue() string {
	if x != nil {
		if x.xxx_hidden_Value != nil {
			return *x.xxx_hidden_Value
		}
		return ""
	}
	return ""
}

func (x *MetadataEvent) SetKey(v string) {
	x.xxx_hidden_Key = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *MetadataEvent) SetValue(v string) {
	x.xxx_hidden_Value = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *MetadataEvent) HasKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MetadataEvent) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MetadataEvent) ClearKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Key = nil
}

func (x *MetadataEvent) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Value = nil
}

type MetadataEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   *string
	Value *string
}

func (b0 MetadataEvent_builder) Build() *MetadataEvent {
	m0 := &MetadataEvent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Key != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Key = b.Key
	}
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Value = b.Value
	}
	return m0
}

type EndEvent struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Timestamp   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp"`
	xxx_hidden_Signal      *string                `protobuf:"bytes,2,opt,name=signal"`
	xxx_hidden_Status      uint32                 `protobuf:"varint,3,opt,name=status"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EndEvent) Reset() {
	*x = EndEvent{}
	mi := &file_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndEvent) ProtoMessage() {}

func (x *EndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EndEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *EndEvent) GetSignal() string {
	if x != nil {
		if x.xxx_hidden_Signal != nil {
			return *x.xxx_hidden_Signal
		}
		return ""
	}
	return ""
}

func (x *EndEvent) GetStatus() uint32 {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return 0
}

func (x *EndEvent) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *EndEvent) SetSignal(v string) {
	x.xxx_hidden_Signal = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *EndEvent) SetStatus(v uint32) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *EndEvent) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *EndEvent) HasSignal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EndEvent) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *EndEvent) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

func (x *EndEvent) ClearSignal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Signal = nil
}

func (x *EndEvent) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Status = 0
}

type EndEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The time that the action ended.
	Timestamp *timestamppb.Timestamp
	// The signal that the process received when it exited.
	Signal *string
	// The exit status code on process exit.
	Status *uint32
}

func (b0 EndEvent_builder) Build() *EndEvent {
	m0 := &EndEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Timestamp = b.Timestamp
	if b.Signal != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Signal = b.Signal
	}
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Status = *b.Status
	}
	return m0
}

type StartEvent struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StartEvent) Reset() {
	*x = StartEvent{}
	mi := &file_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEvent) ProtoMessage() {}

func (x *StartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *StartEvent) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *StartEvent) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *StartEvent) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

type StartEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The time that the action started.
	Timestamp *timestamppb.Timestamp
}

func (b0 StartEvent_builder) Build() *StartEvent {
	m0 := &StartEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Timestamp = b.Timestamp
	return m0
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\bsysgraph\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0esysgraph.proto\"\xb7\x04\n" +
	"\rSysGraphEvent\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12@\n" +
	"\x0eresource_event\x18\x03 \x01(\v2\x17.sysgraph.ResourceEventH\x00R\rresourceEvent\x127\n" +
	"\vchild_event\x18\x04 \x01(\v2\x14.sysgraph.ChildEventH\x00R\n" +
	"childEvent\x124\n" +
	"\n" +
	"exec_event\x18\x05 \x01(\v2\x13.sysgraph.ExecEventH\x00R\texecEvent\x12@\n" +
	"\x0emetadata_event\x18\x06 \x01(\v2\x17.sysgraph.MetadataEventH\x00R\rmetadataEvent\x121\n" +
	"\tend_event\x18\a \x01(\v2\x12.sysgraph.EndEventH\x00R\bendEvent\x127\n" +
	"\vstart_event\x18\b \x01(\v2\x14.sysgraph.StartEventH\x00R\n" +
	"startEvent\x124\n" +
	"\n" +
	"pipe_event\x18\t \x01(\v2\x13.sysgraph.PipeEventH\x00R\tpipeEvent\x121\n" +
	"\tdup_event\x18\n" +
	" \x01(\v2\x12.sysgraph.DupEventH\x00R\bdupEventB\a\n" +
	"\x05event\"\v\n" +
	"\tPipeEvent\"\x98\x01\n" +
	"\bDupEvent\x12\x15\n" +
	"\x06old_fd\x18\x01 \x01(\x05R\x05oldFd\x12\x15\n" +
	"\x06new_fd\x18\x02 \x01(\x05R\x05newFd\x12$\n" +
	"\x0eparent_exec_id\x18\x03 \x01(\tR\fparentExecId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x82\x02\n" +
	"\rResourceEvent\x12.\n" +
	"\bresource\x18\x01 \x01(\v2\x12.sysgraph.ResourceR\bresource\x12@\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2!.sysgraph.ResourceEvent.EventTypeR\teventType\x12)\n" +
	"\aio_info\x18\x03 \x01(\v2\x10.sysgraph.IOInfoR\x06ioInfo\"T\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10EVENT_TYPE_INPUT\x10\x01\x12\x15\n" +
	"\x11EVENT_TYPE_OUTPUT\x10\x02\"4\n" +
	"\n" +
	"ChildEvent\x12&\n" +
	"\x0fchild_action_id\x18\x01 \x01(\tR\rchildActionId\"p\n" +
	"\tExecEvent\x122\n" +
	"\n" +
	"executable\x18\x01 \x01(\v2\x12.sysgraph.ResourceR\n" +
	"executable\x12/\n" +
	"\texec_info\x18\x02 \x01(\v2\x12.sysgraph.ExecInfoR\bexecInfo\"7\n" +
	"\rMetadataEvent\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"t\n" +
	"\bEndEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\x12\x16\n" +
	"\x06status\x18\x03 \x01(\rR\x06status\"F\n" +
	"\n" +
	"StartEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB;Z9github.com/google/oss-rebuild/pkg/sysgraph/proto/sysgraphb\beditionsp\xe9\a"

var file_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_events_proto_goTypes = []any{
	(ResourceEvent_EventType)(0),  // 0: sysgraph.ResourceEvent.EventType
	(*SysGraphEvent)(nil),         // 1: sysgraph.SysGraphEvent
	(*PipeEvent)(nil),             // 2: sysgraph.PipeEvent
	(*DupEvent)(nil),              // 3: sysgraph.DupEvent
	(*ResourceEvent)(nil),         // 4: sysgraph.ResourceEvent
	(*ChildEvent)(nil),            // 5: sysgraph.ChildEvent
	(*ExecEvent)(nil),             // 6: sysgraph.ExecEvent
	(*MetadataEvent)(nil),         // 7: sysgraph.MetadataEvent
	(*EndEvent)(nil),              // 8: sysgraph.EndEvent
	(*StartEvent)(nil),            // 9: sysgraph.StartEvent
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*Resource)(nil),              // 11: sysgraph.Resource
	(*IOInfo)(nil),                // 12: sysgraph.IOInfo
	(*ExecInfo)(nil),              // 13: sysgraph.ExecInfo
}
var file_events_proto_depIdxs = []int32{
	10, // 0: sysgraph.SysGraphEvent.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 1: sysgraph.SysGraphEvent.resource_event:type_name -> sysgraph.ResourceEvent
	5,  // 2: sysgraph.SysGraphEvent.child_event:type_name -> sysgraph.ChildEvent
	6,  // 3: sysgraph.SysGraphEvent.exec_event:type_name -> sysgraph.ExecEvent
	7,  // 4: sysgraph.SysGraphEvent.metadata_event:type_name -> sysgraph.MetadataEvent
	8,  // 5: sysgraph.SysGraphEvent.end_event:type_name -> sysgraph.EndEvent
	9,  // 6: sysgraph.SysGraphEvent.start_event:type_name -> sysgraph.StartEvent
	2,  // 7: sysgraph.SysGraphEvent.pipe_event:type_name -> sysgraph.PipeEvent
	3,  // 8: sysgraph.SysGraphEvent.dup_event:type_name -> sysgraph.DupEvent
	10, // 9: sysgraph.DupEvent.timestamp:type_name -> google.protobuf.Timestamp
	11, // 10: sysgraph.ResourceEvent.resource:type_name -> sysgraph.Resource
	0,  // 11: sysgraph.ResourceEvent.event_type:type_name -> sysgraph.ResourceEvent.EventType
	12, // 12: sysgraph.ResourceEvent.io_info:type_name -> sysgraph.IOInfo
	11, // 13: sysgraph.ExecEvent.executable:type_name -> sysgraph.Resource
	13, // 14: sysgraph.ExecEvent.exec_info:type_name -> sysgraph.ExecInfo
	10, // 15: sysgraph.EndEvent.timestamp:type_name -> google.protobuf.Timestamp
	10, // 16: sysgraph.StartEvent.timestamp:type_name -> google.protobuf.Timestamp
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_sysgraph_proto_init()
	file_events_proto_msgTypes[0].OneofWrappers = []any{
		(*sysGraphEvent_ResourceEvent)(nil),
		(*sysGraphEvent_ChildEvent)(nil),
		(*sysGraphEvent_ExecEvent)(nil),
		(*sysGraphEvent_MetadataEvent)(nil),
		(*sysGraphEvent_EndEvent)(nil),
		(*sysGraphEvent_StartEvent)(nil),
		(*sysGraphEvent_PipeEvent)(nil),
		(*sysGraphEvent_DupEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		EnumInfos:         file_events_proto_enumTypes,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
