// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: sysgraph.proto

package sysgraph

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceType int32

const (
	ResourceType_RESOURCE_TYPE_UNSPECIFIED ResourceType = 0
	// A file resource.
	ResourceType_RESOURCE_TYPE_FILE ResourceType = 1
	// A network address resource.
	ResourceType_RESOURCE_TYPE_NETWORK_ADDRESS ResourceType = 2
	// A pipe resource.
	ResourceType_RESOURCE_TYPE_PIPE ResourceType = 3
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "RESOURCE_TYPE_UNSPECIFIED",
		1: "RESOURCE_TYPE_FILE",
		2: "RESOURCE_TYPE_NETWORK_ADDRESS",
		3: "RESOURCE_TYPE_PIPE",
	}
	ResourceType_value = map[string]int32{
		"RESOURCE_TYPE_UNSPECIFIED":     0,
		"RESOURCE_TYPE_FILE":            1,
		"RESOURCE_TYPE_NETWORK_ADDRESS": 2,
		"RESOURCE_TYPE_PIPE":            3,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_sysgraph_proto_enumTypes[0].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_sysgraph_proto_enumTypes[0]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// The type of a file.
type FileType int32

const (
	FileType_FILE_TYPE_UNSPECIFIED FileType = 0
	FileType_FILE_TYPE_REGULAR     FileType = 1
	FileType_FILE_TYPE_DIRECTORY   FileType = 2
	FileType_FILE_TYPE_SYMLINK     FileType = 3
	FileType_FILE_TYPE_SOCKET      FileType = 4
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "FILE_TYPE_UNSPECIFIED",
		1: "FILE_TYPE_REGULAR",
		2: "FILE_TYPE_DIRECTORY",
		3: "FILE_TYPE_SYMLINK",
		4: "FILE_TYPE_SOCKET",
	}
	FileType_value = map[string]int32{
		"FILE_TYPE_UNSPECIFIED": 0,
		"FILE_TYPE_REGULAR":     1,
		"FILE_TYPE_DIRECTORY":   2,
		"FILE_TYPE_SYMLINK":     3,
		"FILE_TYPE_SOCKET":      4,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_sysgraph_proto_enumTypes[1].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_sysgraph_proto_enumTypes[1]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// A sysgraph is a graph of all actions that occur during an execution.
type SysGraph struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                  *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_EntryPointActionIds []int64                `protobuf:"varint,4,rep,packed,name=entry_point_action_ids,json=entryPointActionIds"`
	xxx_hidden_Metadata            map[string]string      `protobuf:"bytes,2,rep,name=metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Subgraphs           []string               `protobuf:"bytes,5,rep,name=subgraphs"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *SysGraph) Reset() {
	*x = SysGraph{}
	mi := &file_sysgraph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysGraph) ProtoMessage() {}

func (x *SysGraph) ProtoReflect() protoreflect.Message {
	mi := &file_sysgraph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SysGraph) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *SysGraph) GetEntryPointActionIds() []int64 {
	if x != nil {
		return x.xxx_hidden_EntryPointActionIds
	}
	return nil
}

func (x *SysGraph) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *SysGraph) GetSubgraphs() []string {
	if x != nil {
		return x.xxx_hidden_Subgraphs
	}
	return nil
}

func (x *SysGraph) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *SysGraph) SetEntryPointActionIds(v []int64) {
	x.xxx_hidden_EntryPointActionIds = v
}

func (x *SysGraph) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

func (x *SysGraph) SetSubgraphs(v []string) {
	x.xxx_hidden_Subgraphs = v
}

func (x *SysGraph) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SysGraph) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type SysGraph_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The uuid of the sysgraph.
	Id *string
	// The entry point action ids of the sysgraph.
	// These actions should have no parent.
	EntryPointActionIds []int64
	// Arbitrary metadata about the sysgraph.
	Metadata map[string]string
	// The names of the subgraphs that make up this sysgraph. This field is
	// only populated for multi-step executions.
	Subgraphs []string
}

func (b0 SysGraph_builder) Build() *SysGraph {
	m0 := &SysGraph{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_EntryPointActionIds = b.EntryPointActionIds
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Subgraphs = b.Subgraphs
	return m0
}

// An action is a single step in an execution.
type Action struct {
	state                               protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Id                       int64                            `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_SysGraphId               *string                          `protobuf:"bytes,2,opt,name=sys_graph_id,json=sysGraphId"`
	xxx_hidden_StartTime                *timestamppb.Timestamp           `protobuf:"bytes,3,opt,name=start_time,json=startTime"`
	xxx_hidden_EndTime                  *timestamppb.Timestamp           `protobuf:"bytes,4,opt,name=end_time,json=endTime"`
	xxx_hidden_Inputs                   map[string]*ResourceInteractions `protobuf:"bytes,5,rep,name=inputs" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_ExecutableResourceDigest *string                          `protobuf:"bytes,6,opt,name=executable_resource_digest,json=executableResourceDigest"`
	xxx_hidden_Outputs                  map[string]*ResourceInteractions `protobuf:"bytes,7,rep,name=outputs" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Children                 map[int64]*ActionInteraction     `protobuf:"bytes,8,rep,name=children" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_ParentActionId           int64                            `protobuf:"varint,9,opt,name=parent_action_id,json=parentActionId"`
	xxx_hidden_ExecInfo                 *ExecInfo                        `protobuf:"bytes,10,opt,name=exec_info,json=execInfo"`
	xxx_hidden_Parent                   *ActionInteraction               `protobuf:"bytes,12,opt,name=parent"`
	xxx_hidden_Executable               *ResourceInteraction             `protobuf:"bytes,13,opt,name=executable"`
	xxx_hidden_Metadata                 map[string]string                `protobuf:"bytes,14,rep,name=metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_ExitSignal               *string                          `protobuf:"bytes,15,opt,name=exit_signal,json=exitSignal"`
	xxx_hidden_ExitStatus               uint32                           `protobuf:"varint,16,opt,name=exit_status,json=exitStatus"`
	XXX_raceDetectHookData              protoimpl.RaceDetectHookData
	XXX_presence                        [1]uint32
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_sysgraph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_sysgraph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Action) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *Action) GetSysGraphId() string {
	if x != nil {
		if x.xxx_hidden_SysGraphId != nil {
			return *x.xxx_hidden_SysGraphId
		}
		return ""
	}
	return ""
}

func (x *Action) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartTime
	}
	return nil
}

func (x *Action) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_EndTime
	}
	return nil
}

func (x *Action) GetInputs() map[string]*ResourceInteractions {
	if x != nil {
		return x.xxx_hidden_Inputs
	}
	return nil
}

func (x *Action) GetExecutableResourceDigest() string {
	if x != nil {
		if x.xxx_hidden_ExecutableResourceDigest != nil {
			return *x.xxx_hidden_ExecutableResourceDigest
		}
		return ""
	}
	return ""
}

func (x *Action) GetOutputs() map[string]*ResourceInteractions {
	if x != nil {
		return x.xxx_hidden_Outputs
	}
	return nil
}

func (x *Action) GetChildren() map[int64]*ActionInteraction {
	if x != nil {
		return x.xxx_hidden_Children
	}
	return nil
}

func (x *Action) GetParentActionId() int64 {
	if x != nil {
		return x.xxx_hidden_ParentActionId
	}
	return 0
}

func (x *Action) GetExecInfo() *ExecInfo {
	if x != nil {
		return x.xxx_hidden_ExecInfo
	}
	return nil
}

func (x *Action) GetParent() *ActionInteraction {
	if x != nil {
		return x.xxx_hidden_Parent
	}
	return nil
}

func (x *Action) GetExecutable() *ResourceInteraction {
	if x != nil {
		return x.xxx_hidden_Executable
	}
	return nil
}

func (x *Action) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *Action) GetExitSignal() string {
	if x != nil {
		if x.xxx_hidden_ExitSignal != nil {
			return *x.xxx_hidden_ExitSignal
		}
		return ""
	}
	return ""
}

func (x *Action) GetExitStatus() uint32 {
	if x != nil {
		return x.xxx_hidden_ExitStatus
	}
	return 0
}

func (x *Action) SetId(v int64) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 15)
}

func (x *Action) SetSysGraphId(v string) {
	x.xxx_hidden_SysGraphId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 15)
}

func (x *Action) SetStartTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartTime = v
}

func (x *Action) SetEndTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_EndTime = v
}

func (x *Action) SetInputs(v map[string]*ResourceInteractions) {
	x.xxx_hidden_Inputs = v
}

func (x *Action) SetExecutableResourceDigest(v string) {
	x.xxx_hidden_ExecutableResourceDigest = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 15)
}

func (x *Action) SetOutputs(v map[string]*ResourceInteractions) {
	x.xxx_hidden_Outputs = v
}

func (x *Action) SetChildren(v map[int64]*ActionInteraction) {
	x.xxx_hidden_Children = v
}

func (x *Action) SetParentActionId(v int64) {
	x.xxx_hidden_ParentActionId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 15)
}

func (x *Action) SetExecInfo(v *ExecInfo) {
	x.xxx_hidden_ExecInfo = v
}

func (x *Action) SetParent(v *ActionInteraction) {
	x.xxx_hidden_Parent = v
}

func (x *Action) SetExecutable(v *ResourceInteraction) {
	x.xxx_hidden_Executable = v
}

func (x *Action) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

func (x *Action) SetExitSignal(v string) {
	x.xxx_hidden_ExitSignal = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 15)
}

func (x *Action) SetExitStatus(v uint32) {
	x.xxx_hidden_ExitStatus = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 15)
}

func (x *Action) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Action) HasSysGraphId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Action) HasStartTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartTime != nil
}

func (x *Action) HasEndTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EndTime != nil
}

func (x *Action) HasExecutableResourceDigest() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Action) HasParentActionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *Action) HasExecInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExecInfo != nil
}

func (x *Action) HasParent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Parent != nil
}

func (x *Action) HasExecutable() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Executable != nil
}

func (x *Action) HasExitSignal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *Action) HasExitStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *Action) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *Action) ClearSysGraphId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_SysGraphId = nil
}

func (x *Action) ClearStartTime() {
	x.xxx_hidden_StartTime = nil
}

func (x *Action) ClearEndTime() {
	x.xxx_hidden_EndTime = nil
}

func (x *Action) ClearExecutableResourceDigest() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ExecutableResourceDigest = nil
}

func (x *Action) ClearParentActionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_ParentActionId = 0
}

func (x *Action) ClearExecInfo() {
	x.xxx_hidden_ExecInfo = nil
}

func (x *Action) ClearParent() {
	x.xxx_hidden_Parent = nil
}

func (x *Action) ClearExecutable() {
	x.xxx_hidden_Executable = nil
}

func (x *Action) ClearExitSignal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_ExitSignal = nil
}

func (x *Action) ClearExitStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_ExitStatus = 0
}

type Action_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The action id, this must be unique within the sysgraph.
	Id *int64
	// The uuid of the sysgraph this action belongs to.
	SysGraphId *string
	// The start time of the action.
	StartTime *timestamppb.Timestamp
	// The end time of the action.
	EndTime *timestamppb.Timestamp
	// Inputs of this action.
	// Keys are the digest of the Resource message that is being interacted with
	// in canonical format <hash>/<size>.
	//
	// Example: Opening a socket connection, Opening a file descriptor,
	// Reading from a file, receiving a network packet, etc.
	Inputs map[string]*ResourceInteractions
	// Optional resource digest of the executable that ran to create this action.
	// Example: The executable that ran to create a child process,
	ExecutableResourceDigest *string
	// Outputs of this action.
	// Keys are the digest of the Resource message that is being interacted with
	// in canonical format <hash>/<size>.
	//
	// These represent side effects the action had on the contents of some
	// resource. Example: Writing to a file, sending a network packet, etc.
	Outputs map[string]*ResourceInteractions
	// All child actions of this action.
	// Keys are the action ids of the child actions.
	Children map[int64]*ActionInteraction
	// The parent action id of this action.
	ParentActionId *int64
	// Exec information for an action.
	ExecInfo *ExecInfo
	// This is the back edge for the children field above.
	Parent *ActionInteraction
	// The executable that ran to create this action.
	Executable *ResourceInteraction
	// Arbitrary metadata about the action (e.g. gid, uid etc).
	Metadata map[string]string
	// The signal that terminated this action.
	ExitSignal *string
	// The exit status of this action.
	ExitStatus *uint32
}

func (b0 Action_builder) Build() *Action {
	m0 := &Action{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 15)
		x.xxx_hidden_Id = *b.Id
	}
	if b.SysGraphId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 15)
		x.xxx_hidden_SysGraphId = b.SysGraphId
	}
	x.xxx_hidden_StartTime = b.StartTime
	x.xxx_hidden_EndTime = b.EndTime
	x.xxx_hidden_Inputs = b.Inputs
	if b.ExecutableResourceDigest != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 15)
		x.xxx_hidden_ExecutableResourceDigest = b.ExecutableResourceDigest
	}
	x.xxx_hidden_Outputs = b.Outputs
	x.xxx_hidden_Children = b.Children
	if b.ParentActionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 15)
		x.xxx_hidden_ParentActionId = *b.ParentActionId
	}
	x.xxx_hidden_ExecInfo = b.ExecInfo
	x.xxx_hidden_Parent = b.Parent
	x.xxx_hidden_Executable = b.Executable
	x.xxx_hidden_Metadata = b.Metadata
	if b.ExitSignal != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 15)
		x.xxx_hidden_ExitSignal = b.ExitSignal
	}
	if b.ExitStatus != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 15)
		x.xxx_hidden_ExitStatus = *b.ExitStatus
	}
	return m0
}

// An action interaction is a single effect of an action on another action.
type ActionInteraction struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ActionInteraction) Reset() {
	*x = ActionInteraction{}
	mi := &file_sysgraph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionInteraction) ProtoMessage() {}

func (x *ActionInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_sysgraph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ActionInteraction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *ActionInteraction) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *ActionInteraction) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *ActionInteraction) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

type ActionInteraction_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The time that this interaction occurred.
	Timestamp *timestamppb.Timestamp
}

func (b0 ActionInteraction_builder) Build() *ActionInteraction {
	m0 := &ActionInteraction{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Timestamp = b.Timestamp
	return m0
}

// Exec information for an interaction.
type ExecInfo struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Argv             []string               `protobuf:"bytes,1,rep,name=argv"`
	xxx_hidden_Env              []string               `protobuf:"bytes,2,rep,name=env"`
	xxx_hidden_WorkingDirectory *string                `protobuf:"bytes,3,opt,name=working_directory,json=workingDirectory"`
	xxx_hidden_Pid              int64                  `protobuf:"varint,4,opt,name=pid"`
	xxx_hidden_Tid              int64                  `protobuf:"varint,5,opt,name=tid"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ExecInfo) Reset() {
	*x = ExecInfo{}
	mi := &file_sysgraph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecInfo) ProtoMessage() {}

func (x *ExecInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sysgraph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExecInfo) GetArgv() []string {
	if x != nil {
		return x.xxx_hidden_Argv
	}
	return nil
}

func (x *ExecInfo) GetEnv() []string {
	if x != nil {
		return x.xxx_hidden_Env
	}
	return nil
}

func (x *ExecInfo) GetWorkingDirectory() string {
	if x != nil {
		if x.xxx_hidden_WorkingDirectory != nil {
			return *x.xxx_hidden_WorkingDirectory
		}
		return ""
	}
	return ""
}

func (x *ExecInfo) GetPid() int64 {
	if x != nil {
		return x.xxx_hidden_Pid
	}
	return 0
}

func (x *ExecInfo) GetTid() int64 {
	if x != nil {
		return x.xxx_hidden_Tid
	}
	return 0
}

func (x *ExecInfo) SetArgv(v []string) {
	x.xxx_hidden_Argv = v
}

func (x *ExecInfo) SetEnv(v []string) {
	x.xxx_hidden_Env = v
}

func (x *ExecInfo) SetWorkingDirectory(v string) {
	x.xxx_hidden_WorkingDirectory = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *ExecInfo) SetPid(v int64) {
	x.xxx_hidden_Pid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *ExecInfo) SetTid(v int64) {
	x.xxx_hidden_Tid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *ExecInfo) HasWorkingDirectory() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ExecInfo) HasPid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ExecInfo) HasTid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ExecInfo) ClearWorkingDirectory() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_WorkingDirectory = nil
}

func (x *ExecInfo) ClearPid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Pid = 0
}

func (x *ExecInfo) ClearTid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Tid = 0
}

type ExecInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Argv is the command line arguments passed to the action.
	Argv []string
	// Env is the environment variables passed to the action.
	Env []string
	// Working directory is the working directory of the action.
	WorkingDirectory *string
	// The process id of the action.
	Pid *int64
	// The thread id of the action.
	Tid *int64
}

func (b0 ExecInfo_builder) Build() *ExecInfo {
	m0 := &ExecInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Argv = b.Argv
	x.xxx_hidden_Env = b.Env
	if b.WorkingDirectory != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_WorkingDirectory = b.WorkingDirectory
	}
	if b.Pid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Pid = *b.Pid
	}
	if b.Tid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Tid = *b.Tid
	}
	return m0
}

// Resource interactions are a collection of resource interactions by a single
// action on a single resource.
type ResourceInteractions struct {
	state                   protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Interactions *[]*ResourceInteraction `protobuf:"bytes,1,rep,name=interactions"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResourceInteractions) Reset() {
	*x = ResourceInteractions{}
	mi := &file_sysgraph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInteractions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInteractions) ProtoMessage() {}

func (x *ResourceInteractions) ProtoReflect() protoreflect.Message {
	mi := &file_sysgraph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResourceInteractions) GetInteractions() []*ResourceInteraction {
	if x != nil {
		if x.xxx_hidden_Interactions != nil {
			return *x.xxx_hidden_Interactions
		}
	}
	return nil
}

func (x *ResourceInteractions) SetInteractions(v []*ResourceInteraction) {
	x.xxx_hidden_Interactions = &v
}

type ResourceInteractions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The resource interactions for a single acton on a single resource.
	Interactions []*ResourceInteraction
}

func (b0 ResourceInteractions_builder) Build() *ResourceInteractions {
	m0 := &ResourceInteractions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Interactions = &b.Interactions
	return m0
}

// A resource interaction is a single effect of an action on a resource.
type ResourceInteraction struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp"`
	xxx_hidden_IoInfo    *IOInfo                `protobuf:"bytes,4,opt,name=io_info,json=ioInfo"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResourceInteraction) Reset() {
	*x = ResourceInteraction{}
	mi := &file_sysgraph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInteraction) ProtoMessage() {}

func (x *ResourceInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_sysgraph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResourceInteraction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *ResourceInteraction) GetIoInfo() *IOInfo {
	if x != nil {
		return x.xxx_hidden_IoInfo
	}
	return nil
}

func (x *ResourceInteraction) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *ResourceInteraction) SetIoInfo(v *IOInfo) {
	x.xxx_hidden_IoInfo = v
}

func (x *ResourceInteraction) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *ResourceInteraction) HasIoInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_IoInfo != nil
}

func (x *ResourceInteraction) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

func (x *ResourceInteraction) ClearIoInfo() {
	x.xxx_hidden_IoInfo = nil
}

type ResourceInteraction_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The time that this interaction occurred.
	Timestamp *timestamppb.Timestamp
	// I/O information for this interaction.
	// This is optional and may not be populated.
	IoInfo *IOInfo
}

func (b0 ResourceInteraction_builder) Build() *ResourceInteraction {
	m0 := &ResourceInteraction{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Timestamp = b.Timestamp
	x.xxx_hidden_IoInfo = b.IoInfo
	return m0
}

// IO information for an interaction.
type IOInfo struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TotalSizeBytes  uint64                 `protobuf:"varint,1,opt,name=total_size_bytes,json=totalSizeBytes"`
	xxx_hidden_BytesUsed       uint64                 `protobuf:"varint,2,opt,name=bytes_used,json=bytesUsed"`
	xxx_hidden_BytesUsedOffset uint64                 `protobuf:"varint,3,opt,name=bytes_used_offset,json=bytesUsedOffset"`
	xxx_hidden_Flags           []string               `protobuf:"bytes,6,rep,name=flags"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *IOInfo) Reset() {
	*x = IOInfo{}
	mi := &file_sysgraph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOInfo) ProtoMessage() {}

func (x *IOInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sysgraph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IOInfo) GetTotalSizeBytes() uint64 {
	if x != nil {
		return x.xxx_hidden_TotalSizeBytes
	}
	return 0
}

func (x *IOInfo) GetBytesUsed() uint64 {
	if x != nil {
		return x.xxx_hidden_BytesUsed
	}
	return 0
}

func (x *IOInfo) GetBytesUsedOffset() uint64 {
	if x != nil {
		return x.xxx_hidden_BytesUsedOffset
	}
	return 0
}

func (x *IOInfo) GetFlags() []string {
	if x != nil {
		return x.xxx_hidden_Flags
	}
	return nil
}

func (x *IOInfo) SetTotalSizeBytes(v uint64) {
	x.xxx_hidden_TotalSizeBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *IOInfo) SetBytesUsed(v uint64) {
	x.xxx_hidden_BytesUsed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *IOInfo) SetBytesUsedOffset(v uint64) {
	x.xxx_hidden_BytesUsedOffset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *IOInfo) SetFlags(v []string) {
	x.xxx_hidden_Flags = v
}

func (x *IOInfo) HasTotalSizeBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *IOInfo) HasBytesUsed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *IOInfo) HasBytesUsedOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *IOInfo) ClearTotalSizeBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TotalSizeBytes = 0
}

func (x *IOInfo) ClearBytesUsed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_BytesUsed = 0
}

func (x *IOInfo) ClearBytesUsedOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_BytesUsedOffset = 0
}

type IOInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The total size of the resource.
	TotalSizeBytes *uint64
	// The number of bytes used by this action.
	BytesUsed *uint64
	// The offset of the bytes used by this action.
	BytesUsedOffset *uint64
	// Flags for this IO action.
	Flags []string
}

func (b0 IOInfo_builder) Build() *IOInfo {
	m0 := &IOInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TotalSizeBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_TotalSizeBytes = *b.TotalSizeBytes
	}
	if b.BytesUsed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_BytesUsed = *b.BytesUsed
	}
	if b.BytesUsedOffset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_BytesUsedOffset = *b.BytesUsedOffset
	}
	x.xxx_hidden_Flags = b.Flags
	return m0
}

type ResourceWithDigest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Digest      *string                `protobuf:"bytes,1,opt,name=digest"`
	xxx_hidden_Resource    *Resource              `protobuf:"bytes,2,opt,name=resource"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResourceWithDigest) Reset() {
	*x = ResourceWithDigest{}
	mi := &file_sysgraph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceWithDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceWithDigest) ProtoMessage() {}

func (x *ResourceWithDigest) ProtoReflect() protoreflect.Message {
	mi := &file_sysgraph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResourceWithDigest) GetDigest() string {
	if x != nil {
		if x.xxx_hidden_Digest != nil {
			return *x.xxx_hidden_Digest
		}
		return ""
	}
	return ""
}

func (x *ResourceWithDigest) GetResource() *Resource {
	if x != nil {
		return x.xxx_hidden_Resource
	}
	return nil
}

func (x *ResourceWithDigest) SetDigest(v string) {
	x.xxx_hidden_Digest = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ResourceWithDigest) SetResource(v *Resource) {
	x.xxx_hidden_Resource = v
}

func (x *ResourceWithDigest) HasDigest() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ResourceWithDigest) HasResource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Resource != nil
}

func (x *ResourceWithDigest) ClearDigest() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Digest = nil
}

func (x *ResourceWithDigest) ClearResource() {
	x.xxx_hidden_Resource = nil
}

type ResourceWithDigest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The digest of the Resource message in canonical format <hash>/<size>.
	Digest *string
	// The resource message.
	Resource *Resource
}

func (b0 ResourceWithDigest_builder) Build() *ResourceWithDigest {
	m0 := &ResourceWithDigest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Digest != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Digest = b.Digest
	}
	x.xxx_hidden_Resource = b.Resource
	return m0
}

type ResourceDB struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Resources map[string]*Resource   `protobuf:"bytes,1,rep,name=resources" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResourceDB) Reset() {
	*x = ResourceDB{}
	mi := &file_sysgraph_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDB) ProtoMessage() {}

func (x *ResourceDB) ProtoReflect() protoreflect.Message {
	mi := &file_sysgraph_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResourceDB) GetResources() map[string]*Resource {
	if x != nil {
		return x.xxx_hidden_Resources
	}
	return nil
}

func (x *ResourceDB) SetResources(v map[string]*Resource) {
	x.xxx_hidden_Resources = v
}

type ResourceDB_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A map of resource digests in canonical format <hash>/<size> to resource
	// messages.
	Resources map[string]*Resource
}

func (b0 ResourceDB_builder) Build() *ResourceDB {
	m0 := &ResourceDB{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Resources = b.Resources
	return m0
}

type Resource struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type            ResourceType           `protobuf:"varint,2,opt,name=type,enum=sysgraph.ResourceType"`
	xxx_hidden_FileInfo        *FileInfo              `protobuf:"bytes,4,opt,name=file_info,json=fileInfo"`
	xxx_hidden_NetworkAddrInfo *NetworkAddrInfo       `protobuf:"bytes,5,opt,name=network_addr_info,json=networkAddrInfo"`
	xxx_hidden_PipeInfo        *PipeInfo              `protobuf:"bytes,6,opt,name=pipe_info,json=pipeInfo"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_sysgraph_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_sysgraph_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Resource) GetType() ResourceType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *Resource) GetFileInfo() *FileInfo {
	if x != nil {
		return x.xxx_hidden_FileInfo
	}
	return nil
}

func (x *Resource) GetNetworkAddrInfo() *NetworkAddrInfo {
	if x != nil {
		return x.xxx_hidden_NetworkAddrInfo
	}
	return nil
}

func (x *Resource) GetPipeInfo() *PipeInfo {
	if x != nil {
		return x.xxx_hidden_PipeInfo
	}
	return nil
}

func (x *Resource) SetType(v ResourceType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Resource) SetFileInfo(v *FileInfo) {
	x.xxx_hidden_FileInfo = v
}

func (x *Resource) SetNetworkAddrInfo(v *NetworkAddrInfo) {
	x.xxx_hidden_NetworkAddrInfo = v
}

func (x *Resource) SetPipeInfo(v *PipeInfo) {
	x.xxx_hidden_PipeInfo = v
}

func (x *Resource) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Resource) HasFileInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_FileInfo != nil
}

func (x *Resource) HasNetworkAddrInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_NetworkAddrInfo != nil
}

func (x *Resource) HasPipeInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PipeInfo != nil
}

func (x *Resource) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *Resource) ClearFileInfo() {
	x.xxx_hidden_FileInfo = nil
}

func (x *Resource) ClearNetworkAddrInfo() {
	x.xxx_hidden_NetworkAddrInfo = nil
}

func (x *Resource) ClearPipeInfo() {
	x.xxx_hidden_PipeInfo = nil
}

type Resource_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The type of the resource.
	Type *ResourceType
	// File information for this resource.
	// This is optional and may not be populated.
	FileInfo *FileInfo
	// Network address information for this resource.
	// This is optional and may not be populated.
	NetworkAddrInfo *NetworkAddrInfo
	PipeInfo        *PipeInfo
}

func (b0 Resource_builder) Build() *Resource {
	m0 := &Resource{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Type = *b.Type
	}
	x.xxx_hidden_FileInfo = b.FileInfo
	x.xxx_hidden_NetworkAddrInfo = b.NetworkAddrInfo
	x.xxx_hidden_PipeInfo = b.PipeInfo
	return m0
}

// PipeInfo represents a pipe that two child processes communicate through.
// The write end dup action redirect the write end of the pipe to its stdout,
// and the read end dup action redirect the read end of the pipe to its stdin.
type PipeInfo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ReadEnd     *StdIODupInfo          `protobuf:"bytes,1,opt,name=read_end,json=readEnd"`
	xxx_hidden_WriteEnd    *StdIODupInfo          `protobuf:"bytes,2,opt,name=write_end,json=writeEnd"`
	xxx_hidden_ReadExecId  *string                `protobuf:"bytes,3,opt,name=read_exec_id,json=readExecId"`
	xxx_hidden_WriteExecId *string                `protobuf:"bytes,4,opt,name=write_exec_id,json=writeExecId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PipeInfo) Reset() {
	*x = PipeInfo{}
	mi := &file_sysgraph_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeInfo) ProtoMessage() {}

func (x *PipeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sysgraph_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PipeInfo) GetReadEnd() *StdIODupInfo {
	if x != nil {
		return x.xxx_hidden_ReadEnd
	}
	return nil
}

func (x *PipeInfo) GetWriteEnd() *StdIODupInfo {
	if x != nil {
		return x.xxx_hidden_WriteEnd
	}
	return nil
}

func (x *PipeInfo) GetReadExecId() string {
	if x != nil {
		if x.xxx_hidden_ReadExecId != nil {
			return *x.xxx_hidden_ReadExecId
		}
		return ""
	}
	return ""
}

func (x *PipeInfo) GetWriteExecId() string {
	if x != nil {
		if x.xxx_hidden_WriteExecId != nil {
			return *x.xxx_hidden_WriteExecId
		}
		return ""
	}
	return ""
}

func (x *PipeInfo) SetReadEnd(v *StdIODupInfo) {
	x.xxx_hidden_ReadEnd = v
}

func (x *PipeInfo) SetWriteEnd(v *StdIODupInfo) {
	x.xxx_hidden_WriteEnd = v
}

func (x *PipeInfo) SetReadExecId(v string) {
	x.xxx_hidden_ReadExecId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *PipeInfo) SetWriteExecId(v string) {
	x.xxx_hidden_WriteExecId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *PipeInfo) HasReadEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ReadEnd != nil
}

func (x *PipeInfo) HasWriteEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_WriteEnd != nil
}

func (x *PipeInfo) HasReadExecId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PipeInfo) HasWriteExecId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PipeInfo) ClearReadEnd() {
	x.xxx_hidden_ReadEnd = nil
}

func (x *PipeInfo) ClearWriteEnd() {
	x.xxx_hidden_WriteEnd = nil
}

func (x *PipeInfo) ClearReadExecId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ReadExecId = nil
}

func (x *PipeInfo) ClearWriteExecId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_WriteExecId = nil
}

type PipeInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ReadEnd  *StdIODupInfo
	WriteEnd *StdIODupInfo
	// We need the tetragon exec ID here to make each PipeInfo unique.
	// Due to file descriptor recycling, read/write file descriptor numbers are
	// not sufficient to distinguish between different pipes. For example, a
	// parent process may launch multiple pipe actions, and child dup actions
	// might reuse the same file descriptors. Without exec_id, these pipes'
	// digests will be identical.
	ReadExecId  *string
	WriteExecId *string
}

func (b0 PipeInfo_builder) Build() *PipeInfo {
	m0 := &PipeInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ReadEnd = b.ReadEnd
	x.xxx_hidden_WriteEnd = b.WriteEnd
	if b.ReadExecId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_ReadExecId = b.ReadExecId
	}
	if b.WriteExecId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_WriteExecId = b.WriteExecId
	}
	return m0
}

// StdIODupInfo represents a dup action, the new fd can be any number, but the
// old fd is either stdin (fd 0) or stdout (fd 1).
type StdIODupInfo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OldFd       int32                  `protobuf:"varint,1,opt,name=old_fd,json=oldFd"`
	xxx_hidden_NewFd       int32                  `protobuf:"varint,2,opt,name=new_fd,json=newFd"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StdIODupInfo) Reset() {
	*x = StdIODupInfo{}
	mi := &file_sysgraph_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdIODupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdIODupInfo) ProtoMessage() {}

func (x *StdIODupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sysgraph_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StdIODupInfo) GetOldFd() int32 {
	if x != nil {
		return x.xxx_hidden_OldFd
	}
	return 0
}

func (x *StdIODupInfo) GetNewFd() int32 {
	if x != nil {
		return x.xxx_hidden_NewFd
	}
	return 0
}

func (x *StdIODupInfo) SetOldFd(v int32) {
	x.xxx_hidden_OldFd = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *StdIODupInfo) SetNewFd(v int32) {
	x.xxx_hidden_NewFd = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *StdIODupInfo) HasOldFd() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StdIODupInfo) HasNewFd() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StdIODupInfo) ClearOldFd() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_OldFd = 0
}

func (x *StdIODupInfo) ClearNewFd() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NewFd = 0
}

type StdIODupInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OldFd *int32
	NewFd *int32
}

func (b0 StdIODupInfo_builder) Build() *StdIODupInfo {
	m0 := &StdIODupInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.OldFd != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_OldFd = *b.OldFd
	}
	if b.NewFd != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_NewFd = *b.NewFd
	}
	return m0
}

// A file is a single file in the sysgraph.
type FileInfo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path        *string                `protobuf:"bytes,1,opt,name=path"`
	xxx_hidden_Digest      *string                `protobuf:"bytes,2,opt,name=digest"`
	xxx_hidden_Type        FileType               `protobuf:"varint,3,opt,name=type,enum=sysgraph.FileType"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_sysgraph_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sysgraph_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		if x.xxx_hidden_Path != nil {
			return *x.xxx_hidden_Path
		}
		return ""
	}
	return ""
}

func (x *FileInfo) GetDigest() string {
	if x != nil {
		if x.xxx_hidden_Digest != nil {
			return *x.xxx_hidden_Digest
		}
		return ""
	}
	return ""
}

func (x *FileInfo) GetType() FileType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Type
		}
	}
	return FileType_FILE_TYPE_UNSPECIFIED
}

func (x *FileInfo) SetPath(v string) {
	x.xxx_hidden_Path = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *FileInfo) SetDigest(v string) {
	x.xxx_hidden_Digest = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *FileInfo) SetType(v FileType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *FileInfo) HasPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *FileInfo) HasDigest() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *FileInfo) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *FileInfo) ClearPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Path = nil
}

func (x *FileInfo) ClearDigest() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Digest = nil
}

func (x *FileInfo) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Type = FileType_FILE_TYPE_UNSPECIFIED
}

type FileInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The absolute path to the file.
	Path *string
	// The digest of the file in canonical format <hash>/<size>.
	Digest *string
	// The type of the file.
	Type *FileType
}

func (b0 FileInfo_builder) Build() *FileInfo {
	m0 := &FileInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Path != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Path = b.Path
	}
	if b.Digest != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Digest = b.Digest
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Type = *b.Type
	}
	return m0
}

// A network address is a single network address in the sysgraph.
type NetworkAddrInfo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Protocol    *string                `protobuf:"bytes,1,opt,name=protocol"`
	xxx_hidden_Address     *string                `protobuf:"bytes,2,opt,name=address"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NetworkAddrInfo) Reset() {
	*x = NetworkAddrInfo{}
	mi := &file_sysgraph_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAddrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAddrInfo) ProtoMessage() {}

func (x *NetworkAddrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sysgraph_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NetworkAddrInfo) GetProtocol() string {
	if x != nil {
		if x.xxx_hidden_Protocol != nil {
			return *x.xxx_hidden_Protocol
		}
		return ""
	}
	return ""
}

func (x *NetworkAddrInfo) GetAddress() string {
	if x != nil {
		if x.xxx_hidden_Address != nil {
			return *x.xxx_hidden_Address
		}
		return ""
	}
	return ""
}

func (x *NetworkAddrInfo) SetProtocol(v string) {
	x.xxx_hidden_Protocol = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *NetworkAddrInfo) SetAddress(v string) {
	x.xxx_hidden_Address = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *NetworkAddrInfo) HasProtocol() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *NetworkAddrInfo) HasAddress() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *NetworkAddrInfo) ClearProtocol() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Protocol = nil
}

func (x *NetworkAddrInfo) ClearAddress() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Address = nil
}

type NetworkAddrInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The protocol of the network address.
	Protocol *string
	// The network address in string form.
	Address *string
}

func (b0 NetworkAddrInfo_builder) Build() *NetworkAddrInfo {
	m0 := &NetworkAddrInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Protocol != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Protocol = b.Protocol
	}
	if b.Address != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Address = b.Address
	}
	return m0
}

var File_sysgraph_proto protoreflect.FileDescriptor

const file_sysgraph_proto_rawDesc = "" +
	"\n" +
	"\x0esysgraph.proto\x12\bsysgraph\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x01\n" +
	"\bSysGraph\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x16entry_point_action_ids\x18\x04 \x03(\x03R\x13entryPointActionIds\x12<\n" +
	"\bmetadata\x18\x02 \x03(\v2 .sysgraph.SysGraph.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\tsubgraphs\x18\x05 \x03(\tR\tsubgraphs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x03\x10\x04\"\xb6\b\n" +
	"\x06Action\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\fsys_graph_id\x18\x02 \x01(\tR\n" +
	"sysGraphId\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x124\n" +
	"\x06inputs\x18\x05 \x03(\v2\x1c.sysgraph.Action.InputsEntryR\x06inputs\x12<\n" +
	"\x1aexecutable_resource_digest\x18\x06 \x01(\tR\x18executableResourceDigest\x127\n" +
	"\aoutputs\x18\a \x03(\v2\x1d.sysgraph.Action.OutputsEntryR\aoutputs\x12:\n" +
	"\bchildren\x18\b \x03(\v2\x1e.sysgraph.Action.ChildrenEntryR\bchildren\x12(\n" +
	"\x10parent_action_id\x18\t \x01(\x03R\x0eparentActionId\x12/\n" +
	"\texec_info\x18\n" +
	" \x01(\v2\x12.sysgraph.ExecInfoR\bexecInfo\x123\n" +
	"\x06parent\x18\f \x01(\v2\x1b.sysgraph.ActionInteractionR\x06parent\x12=\n" +
	"\n" +
	"executable\x18\r \x01(\v2\x1d.sysgraph.ResourceInteractionR\n" +
	"executable\x12:\n" +
	"\bmetadata\x18\x0e \x03(\v2\x1e.sysgraph.Action.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\vexit_signal\x18\x0f \x01(\tR\n" +
	"exitSignal\x12\x1f\n" +
	"\vexit_status\x18\x10 \x01(\rR\n" +
	"exitStatus\x1aY\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.sysgraph.ResourceInteractionsR\x05value:\x028\x01\x1aZ\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.sysgraph.ResourceInteractionsR\x05value:\x028\x01\x1aX\n" +
	"\rChildrenEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.sysgraph.ActionInteractionR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\v\x10\f\"M\n" +
	"\x11ActionInteraction\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x81\x01\n" +
	"\bExecInfo\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\x12\x10\n" +
	"\x03env\x18\x02 \x03(\tR\x03env\x12+\n" +
	"\x11working_directory\x18\x03 \x01(\tR\x10workingDirectory\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x03R\x03pid\x12\x10\n" +
	"\x03tid\x18\x05 \x01(\x03R\x03tid\"Y\n" +
	"\x14ResourceInteractions\x12A\n" +
	"\finteractions\x18\x01 \x03(\v2\x1d.sysgraph.ResourceInteractionR\finteractions\"z\n" +
	"\x13ResourceInteraction\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12)\n" +
	"\aio_info\x18\x04 \x01(\v2\x10.sysgraph.IOInfoR\x06ioInfo\"\x93\x01\n" +
	"\x06IOInfo\x12(\n" +
	"\x10total_size_bytes\x18\x01 \x01(\x04R\x0etotalSizeBytes\x12\x1d\n" +
	"\n" +
	"bytes_used\x18\x02 \x01(\x04R\tbytesUsed\x12*\n" +
	"\x11bytes_used_offset\x18\x03 \x01(\x04R\x0fbytesUsedOffset\x12\x14\n" +
	"\x05flags\x18\x06 \x03(\tR\x05flags\"\\\n" +
	"\x12ResourceWithDigest\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12.\n" +
	"\bresource\x18\x02 \x01(\v2\x12.sysgraph.ResourceR\bresource\"\xa1\x01\n" +
	"\n" +
	"ResourceDB\x12A\n" +
	"\tresources\x18\x01 \x03(\v2#.sysgraph.ResourceDB.ResourcesEntryR\tresources\x1aP\n" +
	"\x0eResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.sysgraph.ResourceR\x05value:\x028\x01\"\xdf\x01\n" +
	"\bResource\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.sysgraph.ResourceTypeR\x04type\x12/\n" +
	"\tfile_info\x18\x04 \x01(\v2\x12.sysgraph.FileInfoR\bfileInfo\x12E\n" +
	"\x11network_addr_info\x18\x05 \x01(\v2\x19.sysgraph.NetworkAddrInfoR\x0fnetworkAddrInfo\x12/\n" +
	"\tpipe_info\x18\x06 \x01(\v2\x12.sysgraph.PipeInfoR\bpipeInfo\"\xb8\x01\n" +
	"\bPipeInfo\x121\n" +
	"\bread_end\x18\x01 \x01(\v2\x16.sysgraph.StdIODupInfoR\areadEnd\x123\n" +
	"\twrite_end\x18\x02 \x01(\v2\x16.sysgraph.StdIODupInfoR\bwriteEnd\x12 \n" +
	"\fread_exec_id\x18\x03 \x01(\tR\n" +
	"readExecId\x12\"\n" +
	"\rwrite_exec_id\x18\x04 \x01(\tR\vwriteExecId\"<\n" +
	"\fStdIODupInfo\x12\x15\n" +
	"\x06old_fd\x18\x01 \x01(\x05R\x05oldFd\x12\x15\n" +
	"\x06new_fd\x18\x02 \x01(\x05R\x05newFd\"^\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.sysgraph.FileTypeR\x04type\"G\n" +
	"\x0fNetworkAddrInfo\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress*\x80\x01\n" +
	"\fResourceType\x12\x1d\n" +
	"\x19RESOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RESOURCE_TYPE_FILE\x10\x01\x12!\n" +
	"\x1dRESOURCE_TYPE_NETWORK_ADDRESS\x10\x02\x12\x16\n" +
	"\x12RESOURCE_TYPE_PIPE\x10\x03*\x82\x01\n" +
	"\bFileType\x12\x19\n" +
	"\x15FILE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FILE_TYPE_REGULAR\x10\x01\x12\x17\n" +
	"\x13FILE_TYPE_DIRECTORY\x10\x02\x12\x15\n" +
	"\x11FILE_TYPE_SYMLINK\x10\x03\x12\x14\n" +
	"\x10FILE_TYPE_SOCKET\x10\x04B;Z9github.com/google/oss-rebuild/pkg/sysgraph/proto/sysgraphb\beditionsp\xe9\a"

var file_sysgraph_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sysgraph_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_sysgraph_proto_goTypes = []any{
	(ResourceType)(0),             // 0: sysgraph.ResourceType
	(FileType)(0),                 // 1: sysgraph.FileType
	(*SysGraph)(nil),              // 2: sysgraph.SysGraph
	(*Action)(nil),                // 3: sysgraph.Action
	(*ActionInteraction)(nil),     // 4: sysgraph.ActionInteraction
	(*ExecInfo)(nil),              // 5: sysgraph.ExecInfo
	(*ResourceInteractions)(nil),  // 6: sysgraph.ResourceInteractions
	(*ResourceInteraction)(nil),   // 7: sysgraph.ResourceInteraction
	(*IOInfo)(nil),                // 8: sysgraph.IOInfo
	(*ResourceWithDigest)(nil),    // 9: sysgraph.ResourceWithDigest
	(*ResourceDB)(nil),            // 10: sysgraph.ResourceDB
	(*Resource)(nil),              // 11: sysgraph.Resource
	(*PipeInfo)(nil),              // 12: sysgraph.PipeInfo
	(*StdIODupInfo)(nil),          // 13: sysgraph.StdIODupInfo
	(*FileInfo)(nil),              // 14: sysgraph.FileInfo
	(*NetworkAddrInfo)(nil),       // 15: sysgraph.NetworkAddrInfo
	nil,                           // 16: sysgraph.SysGraph.MetadataEntry
	nil,                           // 17: sysgraph.Action.InputsEntry
	nil,                           // 18: sysgraph.Action.OutputsEntry
	nil,                           // 19: sysgraph.Action.ChildrenEntry
	nil,                           // 20: sysgraph.Action.MetadataEntry
	nil,                           // 21: sysgraph.ResourceDB.ResourcesEntry
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_sysgraph_proto_depIdxs = []int32{
	16, // 0: sysgraph.SysGraph.metadata:type_name -> sysgraph.SysGraph.MetadataEntry
	22, // 1: sysgraph.Action.start_time:type_name -> google.protobuf.Timestamp
	22, // 2: sysgraph.Action.end_time:type_name -> google.protobuf.Timestamp
	17, // 3: sysgraph.Action.inputs:type_name -> sysgraph.Action.InputsEntry
	18, // 4: sysgraph.Action.outputs:type_name -> sysgraph.Action.OutputsEntry
	19, // 5: sysgraph.Action.children:type_name -> sysgraph.Action.ChildrenEntry
	5,  // 6: sysgraph.Action.exec_info:type_name -> sysgraph.ExecInfo
	4,  // 7: sysgraph.Action.parent:type_name -> sysgraph.ActionInteraction
	7,  // 8: sysgraph.Action.executable:type_name -> sysgraph.ResourceInteraction
	20, // 9: sysgraph.Action.metadata:type_name -> sysgraph.Action.MetadataEntry
	22, // 10: sysgraph.ActionInteraction.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 11: sysgraph.ResourceInteractions.interactions:type_name -> sysgraph.ResourceInteraction
	22, // 12: sysgraph.ResourceInteraction.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 13: sysgraph.ResourceInteraction.io_info:type_name -> sysgraph.IOInfo
	11, // 14: sysgraph.ResourceWithDigest.resource:type_name -> sysgraph.Resource
	21, // 15: sysgraph.ResourceDB.resources:type_name -> sysgraph.ResourceDB.ResourcesEntry
	0,  // 16: sysgraph.Resource.type:type_name -> sysgraph.ResourceType
	14, // 17: sysgraph.Resource.file_info:type_name -> sysgraph.FileInfo
	15, // 18: sysgraph.Resource.network_addr_info:type_name -> sysgraph.NetworkAddrInfo
	12, // 19: sysgraph.Resource.pipe_info:type_name -> sysgraph.PipeInfo
	13, // 20: sysgraph.PipeInfo.read_end:type_name -> sysgraph.StdIODupInfo
	13, // 21: sysgraph.PipeInfo.write_end:type_name -> sysgraph.StdIODupInfo
	1,  // 22: sysgraph.FileInfo.type:type_name -> sysgraph.FileType
	6,  // 23: sysgraph.Action.InputsEntry.value:type_name -> sysgraph.ResourceInteractions
	6,  // 24: sysgraph.Action.OutputsEntry.value:type_name -> sysgraph.ResourceInteractions
	4,  // 25: sysgraph.Action.ChildrenEntry.value:type_name -> sysgraph.ActionInteraction
	11, // 26: sysgraph.ResourceDB.ResourcesEntry.value:type_name -> sysgraph.Resource
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_sysgraph_proto_init() }
func file_sysgraph_proto_init() {
	if File_sysgraph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sysgraph_proto_rawDesc), len(file_sysgraph_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sysgraph_proto_goTypes,
		DependencyIndexes: file_sysgraph_proto_depIdxs,
		EnumInfos:         file_sysgraph_proto_enumTypes,
		MessageInfos:      file_sysgraph_proto_msgTypes,
	}.Build()
	File_sysgraph_proto = out.File
	file_sysgraph_proto_goTypes = nil
	file_sysgraph_proto_depIdxs = nil
}
