// Copyright 2025 Google LLC
// SPDX-License-Identifier: Apache-2.0

package stabilize

import (
	"bytes"
	"io"
	"path"
	"regexp"
	"slices"
	"sort"
	"strings"

	"github.com/google/oss-rebuild/internal/glob"
	"github.com/google/oss-rebuild/pkg/archive"
)

// AllJarStabilizers is the list of all available JAR stabilizers.
var AllJarStabilizers = []Stabilizer{
	StableJARBuildMetadata,
	StableJAROrderOfAttributeValues,
	StableGitProperties,
	StableMavenPomProperties,
	StableJarSignature,
}

// StableJARBuildMetadata removes build-related metadata from MANIFEST.MF files.
var StableJARBuildMetadata = Stabilizer{
	Name: "jar-build-metadata",
}.WithFn(ZipEntryFn(func(zf *archive.MutableZipFile) {
	// Only process MANIFEST.MF files
	if !strings.HasSuffix(zf.Name, "META-INF/MANIFEST.MF") {
		return
	}
	r, err := zf.Open()
	if err != nil {
		return
	}
	manifest, err := ParseManifest(r)
	if err != nil {
		return
	}
	for _, attr := range []string{
		"Archiver-Version",
		"Bnd-LastModified",
		"Build-Date",
		"Build-Date-UTC",
		"Build-Host",
		"Build-Id",
		"Build-Java-Version",
		"Build-Jdk",
		"Build-Jdk-Spec",
		"Build-Job",
		"Build-Number",
		"Build-OS",
		"Build-Status",
		"Build-Time",
		"Build-Timestamp",
		"Build-Tool",
		"Build-Url",
		"Built-By",
		"Built-Date",
		"Built-Host",
		"Built-JDK",
		"Built-On",
		"Built-OS",
		"Built-Status",
		"Created-By",
		"DSTAMP",
		"Eclipse-SourceReferences",
		"Git-Branch",
		"Git-Commit-Id-Describe",
		"Git-Remote-Origin-Url",
		"Git-SHA",
		"Git-Descriptor",
		"git-describe",
		"git-tags",
		"hash",
		"Hudson-Build-Number",
		"Implementation-Build-Date",
		"Implementation-Build-Java-Vendor",
		"Implementation-Build-Java-Version",
		"Implementation-Build",
		"Ion-Java-Build-Time",
		"Java-Vendor",
		"Java-Version",
		"JCabi-Date",
		"Jenkins-Build-Number",
		"Maven-Version",
		"Module-Origin",
		"Originally-Created-By",
		"Os-Arch",
		"Os-Name",
		"Os-Version",
		"SCM-Git-Branch",
		"SCM-Git-Commit-Dirty",
		"SCM-Git-Commit-ID",
		"SCM-Git-Commit-Abbrev",
		"SCM-Git-Commit-Description",
		"SCM-Git-Commit-Timestamp",
		"SCM-Revision",
		"SHA-256-Digest",
		"Source-Date-Epoch",
		"Sunset-BuiltOn",
		"TODAY",
		"Tool",
		"TSTAMP",
		"X-Compile-Release-JDK",
		"url",
	} {
		manifest.MainSection.Delete(attr)
	}
	buf := bytes.NewBuffer(nil)
	if err := WriteManifest(buf, manifest); err != nil {
		return
	}
	zf.SetContent(buf.Bytes())
}))

// StableJAROrderOfAttributeValues sorts attribute values in MANIFEST.MF files.
var StableJAROrderOfAttributeValues = Stabilizer{
	Name: "jar-attribute-value-order",
}.WithFn(ZipEntryFn(func(zf *archive.MutableZipFile) {
	if !strings.HasSuffix(zf.Name, "META-INF/MANIFEST.MF") {
		return
	}
	r, err := zf.Open()
	if err != nil {
		return
	}
	manifest, err := ParseManifest(r)
	if err != nil {
		return
	}
	// These attributes originate from bnd tool. Full list: https://bnd.bndtools.org/chapters/800-headers.html.
	// Out of these, we only sort the values of the following attributes because we observed them in Reproducible
	// Central dataset. https://github.com/chains-project/reproducible-central/issues/21#issuecomment-2600947048
	for _, attr := range []string{
		"Export-Package",
		"Include-Resource",
		"Provide-Capability",
		"Private-Package",
	} {
		value, _ := manifest.MainSection.Get(attr)
		// Skip empty values
		if value == "" {
			continue
		}
		subvalues := splitPreservingQuotes(value, ',')
		// We sort the values to ensure that the order of values is stable
		// Related issues: 1) [fix for Export-Package & Private-Package](https://github.com/bndtools/bnd/issues/5021)
		// 2) [fix for Include-Resource](https://github.com/jvm-repo-rebuild/reproducible-central/issues/99)
		sort.Strings(subvalues)
		for i, subvalue := range subvalues {
			subvalueArray := splitPreservingQuotes(subvalue, ';')
			sort.Strings(subvalueArray)
			subvalues[i] = strings.Join(subvalueArray, ";")
		}
		manifest.MainSection.Set(attr, strings.Join(subvalues, ","))
	}
	buf := bytes.NewBuffer(nil)
	if err := WriteManifest(buf, manifest); err != nil {
		return
	}
	zf.SetContent(buf.Bytes())
}))

// splitPreservingQuotes splits a string by a separator while preserving quoted sections
func splitPreservingQuotes(s string, sep rune) []string {
	var result []string
	var current strings.Builder
	inQuote := false
	for _, char := range s {
		switch char {
		case '"':
			inQuote = !inQuote
			current.WriteRune(char)
		case sep:
			if inQuote {
				current.WriteRune(char)
			} else {
				result = append(result, current.String())
				current.Reset()
			}
		default:
			current.WriteRune(char)
		}
	}
	// Add the last segment
	if current.Len() > 0 {
		result = append(result, current.String())
	}
	return result
}

// mavenPomPropertiesHeaderRe matches maven-archiver's two-line header.
var mavenPomPropertiesHeaderRe = regexp.MustCompile(`\A#Generated by Maven\r?\n#[^\r\n]*\r?\n`)

// StableMavenPomProperties strips the two-line header emitted by maven-archiver
// in META-INF/maven/<groupId>/<artifactId>/pom.properties.
var StableMavenPomProperties = Stabilizer{
	Name: "jar-maven-pom-properties",
}.WithFn(ZipEntryFn(func(zf *archive.MutableZipFile) {
	if !strings.HasSuffix(zf.Name, "/pom.properties") || !strings.HasPrefix(zf.Name, "META-INF/maven/") {
		return
	}
	r, err := zf.Open()
	if err != nil {
		return
	}
	data, err := io.ReadAll(r)
	if err != nil {
		return
	}
	zf.SetContent(mavenPomPropertiesHeaderRe.ReplaceAll(data, nil))
}))

// jarSignaturePatterns matches the jarsigner signature artifact files.
var jarSignaturePatterns = []string{
	"META-INF/*.SF",
	"META-INF/*.RSA",
	"META-INF/*.DSA",
	"META-INF/*.EC",
}

// jarDigestAttrs is the set of MANIFEST.MF per-entry attribute names that jarsigner writes alongside Name.
var jarDigestAttrs = []string{
	"MD5-Digest",
	"SHA-1-Digest",
	"SHA-256-Digest",
	"SHA-384-Digest",
	"SHA-512-Digest",
	// Legacy pre-JDK8 names omitted hyphens
	"SHA-Digest",
	"SHA1-Digest",
}

// StableJarSignature removes jarsigner output so comparison is independent of signatures.
//
// On signed jars,
// - drop the signature artifacts (.SF / .RSA / .DSA / .EC)
// - filters *-Digest attributes added to MANIFEST.MF
//
// NOTE: Transforms only applied when a META-INF/*.SF file is present (the
// canonical indication that jarsigner was run).
var StableJarSignature = Stabilizer{
	Name: "jar-signature",
}.WithFn(ZipArchiveFn(func(mr *archive.MutableZipReader) {
	if !hasJarSignature(mr) {
		return
	}
	mr.File = slices.DeleteFunc(mr.File, func(mf *archive.MutableZipFile) bool {
		match, _ := multiMatch(jarSignaturePatterns, mf.Name)
		return match
	})
	for _, mf := range mr.File {
		if mf.Name != "META-INF/MANIFEST.MF" {
			continue
		}
		stripManifestDigestSections(mf)
	}
}))

func hasJarSignature(mr *archive.MutableZipReader) bool {
	for _, mf := range mr.File {
		if match, _ := glob.Match("META-INF/*.SF", mf.Name); match {
			return true
		}
	}
	return false
}

// stripManifestDigestSections inverts the per-entry manifest edits jarsigner makes when signing.
//
// The jarsigner logic we are undoing adds file digests to the manifest one of
// two ways (see JarSigner.{updateDigests,getDigestAttributes}):
//   - When entry already has a manifest section: add an <alg>-Digest attribute
//     and leave its other attributes untouched.
//   - When entry has no section: create a new section holding only Name and the
//     <alg>-Digest attribute(s) (only applied to non-directory entries).
func stripManifestDigestSections(mf *archive.MutableZipFile) {
	r, err := mf.Open()
	if err != nil {
		return
	}
	manifest, err := ParseManifest(r)
	if err != nil {
		return
	}
	kept := manifest.EntrySections[:0]
	for _, sec := range manifest.EntrySections {
		for _, a := range jarDigestAttrs {
			sec.Delete(a)
		}
		if len(sec.Names) > 1 || (len(sec.Names) == 1 && sec.Names[0] != "Name") {
			kept = append(kept, sec)
		}
	}
	manifest.EntrySections = kept
	buf := bytes.NewBuffer(nil)
	if err := WriteManifest(buf, manifest); err != nil {
		return
	}
	mf.SetContent(buf.Bytes())
}

// StableGitProperties clears git.json and git.properties files.
var StableGitProperties = Stabilizer{
	Name: "jar-git-properties",
}.WithFn(ZipEntryFn(func(zf *archive.MutableZipFile) {
	// These files contain git properties set by git-commit-id-maven-plugin.
	// They contain many unreproducible attributes as documented
	// [here](https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/825).
	// Only JSON and properties file formats are available as documented
	// [here](https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/95d616fc7e16018deff3f17e2d03a4b217e55294/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java#L454).
	// By default, these file are created in ${project.build.outputDirectory} and are hence at the root of the jar.
	// We assume that the file name is 'git' as this is the default value for the plugin.
	// We don't handle the case where the file name is changed by the user.
	if path.Base(zf.Name) == "git.json" {
		zf.SetContent([]byte("{}"))
	}
	if path.Base(zf.Name) == "git.properties" {
		zf.SetContent([]byte{})
	}
}))
