# inference differs:
#   registry_time: 2026-01-13T01:14:52Z (inferred: 2026-01-13T01:14:51Z)
#   repo: https://github.com/sdispater/tomlkit (inferred: https://github.com/python-poetry/tomlkit)
pypi_pure_wheel_build:
  location:
    repo: https://github.com/sdispater/tomlkit
    ref: 090a28e46b58473210a74ec68a3c08b1535ff233
  requirements:
    - poetry-core==2.2.1
    - setuptools==67.7.2
  registry_time: "2026-01-13T01:14:52Z"
