# inference differs:
#   requirements: removed setuptools==67.7.2 (vs inferred)
pypi_pure_wheel_build:
  location:
    repo: https://github.com/pygments/pygments
    ref: 708197d82827ba2d5ca78bcbb653c7102ce86dcd
  requirements:
    - hatchling==1.29.0
  registry_time: "2026-03-29T13:29:30Z"
