# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
exclude:
  # NOTE: This list implicitly contains native excludes defined by GitHub pages.
  - CNAME
