# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
exclude:
  - CNAME
  - Gemfile
  - Dockerfile
  - run.sh
logo: https://raw.githubusercontent.com/google/oss-rebuild/main/site/logo-dark.svg
title: OSS Rebuild
