# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

# Gemfile for local Jekyll development
source "https://rubygems.org"
# GitHub Pages requirements
gem "github-pages", group: :jekyll_plugins
gem "jekyll-remote-theme"
# Local development aide
gem "webrick"
