name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.26", "1.27"]

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: ${{matrix.go-version}}

      - name: Build
        run: go run ./ci -v build

      - name: Test
        run: go run ./ci -v test

      - name: Lint
        run: go run ./ci -v lint

      - name: Check formatting
        run: go run ./ci -v fmt-check

      - name: Check imports
        run: go run ./ci -v imports-check

      - name: Check license headers
        run: go run ./ci -v license-check
