name: TF Format

on:
  push:
    branches: ["main"]
    paths: ["**/*.tf"]
  pull_request:
    branches: ["main"]
    paths: ["**/*.tf"]

permissions:
  contents: read

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@9d84900f3238fab8cd84ce47d658d25dd008be2f # v1.0.8

      - name: OpenTofu Format Check
        run: tofu fmt -check -recursive
