name: Markup format

on:
  push:
    branches: ["main"]
    paths: ["**/*.md", "**/*.yml", "**/*.yaml"]
  pull_request:
    branches: ["main"]
    paths: ["**/*.md", "**/*.yml", "**/*.yaml"]

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "18"
          cache: "npm"

      - name: Install
        run: npm ci --save-dev

      - name: Check formatting
        run: |
          npx prettier --version
          npx prettier --check --no-error-on-unmatched-pattern **/*.md **/*.yml **/*.yaml
